application: colabeo
version: 3
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /contact/contact.php
  script: contact/contact.php


- url: /contact/helloworld.php
  script: contact/helloworld.php

- url: /css
  static_dir: css

- url: /fonts
  static_dir: fonts

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /skin
  static_dir: skin

- url: /install.html
  script: install.html

- url: .*
  script: index.html
